server:
  port: 8080
  servlet:
    session:
      timeout: 60m
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: ${CC_DB_URL}
    username: root
    password: ${CC_DB_PASSWORD}
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
        format_sql: true
  jackson:
    locale: ko_KR
    time-zone: Asia/Seoul
#logging:
 ##  root: debug
